#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom
obj-$(CONFIG_MTK_LENS_DUMMYLENS_SUPPORT) +=  mt6582/dummy_lens/
obj-$(CONFIG_MTK_LENS_OV5648AF_SUNWIN_SUPPORT) +=  mt6582/ov5648af_sunwin/
